### ISSUE TITLE
ECKeyComparator fix does not work

### ISSUE THREAD

**Issue by albrechta** [coinblesk/coinblesk-client-gui#21]
The fix with reflection does not work (maybe... not tested on Nexus device). There is an error in the log (exception is not printed, only the message).

Stacktrace
```
3-11 17:28:41.239  16489-16489/com.uzh.ckiller.coinblesk_client_clean_start D/ch.papers.payments.Utils﹕ error during ECKeyComparator fix: modifiers
    java.lang.NoSuchFieldException: modifiers
            at java.lang.Class.getDeclaredField(Class.java:886)
            at ch.papers.payments.Utils.setFinalStatic(Utils.java:95)
            at ch.papers.payments.Utils.fixECKeyComparator(Utils.java:85)
            at ch.papers.payments.WalletService.onStartCommand(WalletService.java:335)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2939)
            at android.app.ActivityThread.access$2100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5349)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by albrechta** [comment]
https://stackoverflow.com/questions/11185453/android-changing-private-static-final-field-using-java-reflection
