### ISSUE TITLE
NPE in transaction detail activity if wallet is not fully loaded yet

### ISSUE THREAD

**Issue by albrechta** [coinblesk/coinblesk-client-gui#63]
If wallet appkit is not finished with the initialization, kit.wallet() returns null.
Happens if e.g. screen is rotated in Tx detail activity.

```
04-15 23:57:20.641 7683-7683/com.coinblesk.client E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.coinblesk.client, PID: 7683
java.lang.NullPointerException: Attempt to invoke virtual method 'org.bitcoinj.core.Transaction org.bitcoinj.core.Wallet.getTransaction(org.bitcoinj.core.Sha256Hash)' on a null object reference
    at com.coinblesk.payments.WalletService$WalletServiceBinder.getTransaction(WalletService.java:292)
    at com.coinblesk.client.TransactionDetailActivity.setTransactionDetails(TransactionDetailActivity.java:93)
    at com.coinblesk.client.TransactionDetailActivity.access$100(TransactionDetailActivity.java:54)
    at com.coinblesk.client.TransactionDetailActivity$3.onServiceConnected(TransactionDetailActivity.java:184)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1336)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1353)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5349)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by dcale** [comment]
fixed
